### PR TITLE
macros

### PR DESCRIPTION
**Pull request by quanvuong**
http://giphy.com/gifs/2pm-macro-gif-y9ZibZs0TBfoI

### CODE REVIEW

**Comment by quanvuong** [comment]
@vasilyrud

**Comment by vasilyrud** [comment]
Sorry about the test function declaration, I got confused.

As for the rest, mostly is good. I like how simple some of your bit-wise functions are.

**Comment by quanvuong** [comment]
ok did all the changes.

can you review again ? @vasilyrud

**Comment by vasilyrud** [comment]
Looks good! I will rebase onto it after you push to master and start using the macros.

@quanvuong 

Actually, I think it is enough for a user to be referred to with "@" once for it to have effect.

**Comment by quanvuong** [comment]
awesome. Thanks man!

I wish GitHub allows you to reply to comment directly in email.

**Pull request merged**
